### ISSUE TITLE
 Setup Kanban Board

### ISSUE THREAD

**Issue by rashedarman** [rashedarman/rails-recipe-app#11]
Hi there :wave:

We have set up our Kanban board from the project requirements.

Project: [rails-recipe-app](https://github.com/rashedarman/rails-recipe-app)
Kanban: [Recipe App](https://github.com/users/rashedarman/projects/2)

Team: @rashedarman and @Booze33 

Thank you.

**Comment by DammyShittu** [comment]
Hi @rashedarman and @Booze33,

While you made a great effort in this project, I cannot proceed to review your code.

## Invalid Code Review Request

### You have submitted an issue that does not have the kanban link.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by DammyShittu** [comment]
Hi @rashedarman and @Booze33,

## Highlights
✔️ Assigned tasks

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] Kindly add a description for these tasks.

  ![image](https://github.com/rashedarman/rails-recipe-app/assets/54848363/66170180-31f7-4492-ba04-a5acbb3248e5)

  ![image](https://github.com/rashedarman/rails-recipe-app/assets/54848363/37acb771-8478-43a4-a8b0-afdc8eb502ea)

  ![image](https://github.com/rashedarman/rails-recipe-app/assets/54848363/76ed3664-51fd-4858-bbbf-3108ee875445)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by DammyShittu** [comment]
Hi @rashedarman and @Booze33,

## APPROVED 🟢

## Highlights
✔️ Assigned tasks

Great implementation of all the requirements in this milestone. 👏 

_You have done an amazing job 👍_

Your project is complete!  There is nothing else to say other than... it's time to merge it. :shipit: 

Congratulations! 🎉 

## CHEERS AND HAPPY CODING!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
